services:
  #Mongo
  mongo-db:
    container_name: mongo-db
    image: mongo:8.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  #SQL
  db:
    container_name: db-postgres
    image: postgres:13
    restart: always
    environment:
      #example config
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digimon_db
    ports:
      - "5432:5432"  # Expose MySQL port to the host
