spring:
  # SQL
  flyway:
    enabled: true  # Enable Flyway for database migrations
    locations: classpath:db/migration  # Location of Flyway migration scripts
    url: jdbc:postgresql://localhost:5432/digimon_db
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/digimon_db
    username: my_user
    password: password
